---
title: Exploring the associations between personality and response speed trajectories in low-stakes intelligence tests
author: Nils Myszkowski
date: '2022-03-03'
slug: []
categories: [Item-Response Theory, Response times, Logical Reasoning, Personality]
tags: []
excerpt: In this paper, using log-normal Item-Response Theory models for response time data, we study how personality traits predict response speed trajectories in low-stakes reasoning tasks. We found that some traits are associated with increasing in speed vs. decreasing in speed, controlling for item effects.
links:
- icon: file-pdf
  icon_pack: fa
  name: PDF
  url: Myszkowski - 2022 - Exploring the associations between personality and.pdf
---

# What it's about

In this paper, using Log-Normal Item-Response Theory models for response time data, we study how personality traits predict response speed trajectories in low-stakes reasoning tasks. We found that some traits are associated with increasing in speed vs. decreasing in speed, controlling for item effects.

# Abstract

Previous research suggests a negative relationship between test taking speed and performance in mental ability testing, inviting researchers to explore the origin of individual differences in test taking speed. We investigate how personality could explain both one's initial speed and its evolution through test completion. 555 adult participants responded the Big Five personality items from the Synthetic Aperture Personality Assessment (SAPA) and a progressive matrices test created with IMak. We used the joint hierarchical response-response time model with variable speed to estimate individual speed parameters (as well as ability). We use Latent Profile Analysis on these person speed estimates, which suggest three distinct profiles. We then interpret these three speed profiles and investigate their relations with Big Five traits. Classes significantly differ on agreeableness, conscientiousness and openness – as well as the matrices test ability. “Hasty” (class 1) individuals are characterized by low openness and ability, “absorbed” (class 2) individuals by high ability and openness, low agreeableness and conscientiousness, and “precautious” (class 3) individuals by high agreeableness and conscientiousness. We conclude that response speed trajectories are associated with ability and personality traits, warranting future investigations.


# How to access the paper

You can access the full paper [here](http://dx.doi.org/10.1016/j.paid.2022.111580).

